collections:
  - name: "products"
    label: "Товары"
    label_singular: "Товар"
    description: "Управление карточками товаров"
    files:
      - file: "products.json"
        label: "Каталог товаров"
        name: "products"
        format: "json"
        fields:
          - label: "Товары"
            name: ""
            widget: "list"
            allow_add: true
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
              - label: "Название"
                name: "name"
                widget: "string"
              - label: "Подзаголовок"
                name: "subtitle"
                widget: "string"
                required: false
              - label: "Описание"
                name: "description"
                widget: "text"
              - label: "Цена"
                name: "price"
                widget: "number"
              - label: "Главное изображение"
                name: "image"
                widget: "string"
              - label: "Изображение (детально)"
                name: "imageLarge"
                widget: "string"
              - label: "Миниатюры"
                name: "thumbs"
                widget: "list"
                field:
                  label: "Изображение"
                  name: "thumb"
                  widget: "string"
              - label: "Характеристики"
                name: "specs"
                widget: "list"
                fields:
                  - label: "Название"
                    name: "label"
                    widget: "string"
                  - label: "Значение"
                    name: "value"
                    widget: "text"
              - label: "Категория"
                name: "category"
                widget: "string"
