backend:
  name: test-repo

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "test"
    label: "Test Collection"
    folder: "content/test"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
